# **Part 1: Exercise Numpy**

## **Jangan di-run! Save sebagai file baru dan edit file tersebut untuk menjawab pertanyaan**

In [11]:
import numpy as np
import pandas as pd

<hr>

### **Nomor 1**

Buatlah sebuah array 1D dengan nama variable myArray yang terdiri dari 36 angka bilangan bulat acak antara 1 dan 100! (Gunakan seed=0)

In [12]:
np.random.seed(0)
myArray = np.random.randint(1, 101, 36)
myArray

array([ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
        13,  59,  66,  40,  88,  47,  89,  82,  38,  26,  78,  73,  10,
        21,  81,  70,  80,  48,  65,  83, 100,  89,  50], dtype=int32)

<hr>

### **Nomor 2**

Ubahlah array tersebut (myArray) menjadi

* array 2D dengan ukuran 2 x 18
* array 2D dengan ukuran 9 x 4
* array 3D dengan ukuran 2 x 6 X 3

In [13]:
myArray2D_1 = myArray.reshape(2, 18)
myArray2D_1

array([[ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88,  71,  89,  89,
         13,  59,  66,  40,  88],
       [ 47,  89,  82,  38,  26,  78,  73,  10,  21,  81,  70,  80,  48,
         65,  83, 100,  89,  50]], dtype=int32)

In [14]:
myArray2D_2 = myArray.reshape(9, 4)
myArray2D_2

array([[ 45,  48,  65,  68],
       [ 68,  10,  84,  22],
       [ 37,  88,  71,  89],
       [ 89,  13,  59,  66],
       [ 40,  88,  47,  89],
       [ 82,  38,  26,  78],
       [ 73,  10,  21,  81],
       [ 70,  80,  48,  65],
       [ 83, 100,  89,  50]], dtype=int32)

In [15]:
myArray3D_1 = myArray.reshape(2, 6, 3)
myArray3D_1

array([[[ 45,  48,  65],
        [ 68,  68,  10],
        [ 84,  22,  37],
        [ 88,  71,  89],
        [ 89,  13,  59],
        [ 66,  40,  88]],

       [[ 47,  89,  82],
        [ 38,  26,  78],
        [ 73,  10,  21],
        [ 81,  70,  80],
        [ 48,  65,  83],
        [100,  89,  50]]], dtype=int32)

<hr>

### **Nomor 3**

Buatlah array baru dengan nama variable new_array yang berisi 9 angka yang diambil dari data pada index ke-3, 5, 30, 12, 15, 8, 24, 14, dan 22 dari myArray!

Ubahlah array tersebut menjadi array 2D dengan ukuran 3 x 3 secara permanen!


In [16]:
new_array = myArray[[3, 5, 30, 12, 15, 8, 24, 14, 22]].reshape(3, 3)
new_array

array([[68, 10, 48],
       [89, 66, 37],
       [73, 59, 26]], dtype=int32)

# **Part 2: Exercise Pandas**

**Membuat DataFrame**

Ikuti semua petunjuk yang harus dilakukan di bawah ini.

### **Nomor 4**

**Buat dictionary untuk membuat DataFrame berjumlah 6 keys dan masing-masing key memiliki value berupa list dengan 10 item. Isi dari dictionary  mengikuti output Nomor 5.**

In [17]:
karyawan = {
    'Nama' : ['Andi', 'Budi', 'Caca', 'Dedi', 'Erika', 'Fahri', 'Gina', 'Hani', 'Indro', 'Jarot'],
    'Gender' : ['Pria', 'Pria', 'Wanita', 'Pria', 'Wanita', 'Pria', 'Wanita', 'Wanita', 'Pria', 'Pria' ],
    'Umur' : [24, 25, 30, 32, 28, 24, 29, 31, 30, 29],
    'Domisili' : ['Jakarta', 'Tangerang Selatan', 'Jakarta', 'Bandung', 'Jakarta', 'Surabaya', 'Bandung', 'Yogyakarta', 'Jakarta', 'Tangerang Selatan'],
    'Pekerjaan' : ['Data Analyst', 'Data Engineer', 'Data Scientist', 'Data Scientist', 'Data Analyst', 'Data Engineer', 'ML Engineer', 'ML Researcher', 'BI Analyst', 'Data Analyst'],
    'Hobi' : ['Gaming', 'Futsal', 'Baca', 'Gaming', 'Masak', 'Traveling', 'Basket', 'Traveling', 'Gaming', 'Futsal']
}

### **Nomor 5**

**Ubah dictionary dari Nomor 4 menjadi bentuk DataFrame dan simpan ke dalam variabel baru bernama `df`.**

In [18]:
df = pd.DataFrame(karyawan)
df

Nama  Gender  Umur           Domisili       Pekerjaan       Hobi
0   Andi    Pria    24            Jakarta    Data Analyst     Gaming
1   Budi    Pria    25  Tangerang Selatan   Data Engineer     Futsal
2   Caca  Wanita    30            Jakarta  Data Scientist       Baca
3   Dedi    Pria    32            Bandung  Data Scientist     Gaming
4  Erika  Wanita    28            Jakarta    Data Analyst      Masak
5  Fahri    Pria    24           Surabaya   Data Engineer  Traveling
6   Gina  Wanita    29            Bandung     ML Engineer     Basket
7   Hani  Wanita    31         Yogyakarta   ML Researcher  Traveling
8  Indro    Pria    30            Jakarta      BI Analyst     Gaming
9  Jarot    Pria    29  Tangerang Selatan    Data Analyst     Futsal

### **Nomor 6**
**Gunakan**:
- `.iloc` untuk mengambil data Dedi, Fahri, Hani
- `.loc` untuk mengambil data Dedi, Fahri, Hani

In [19]:
df.iloc[[3, 5, 7]]


Nama  Gender  Umur    Domisili       Pekerjaan       Hobi
3   Dedi    Pria    32     Bandung  Data Scientist     Gaming
5  Fahri    Pria    24    Surabaya   Data Engineer  Traveling
7   Hani  Wanita    31  Yogyakarta   ML Researcher  Traveling

### **Nomor 7**
**Gunakan**:
- `loc`  untuk menampilkan domisili dan pekerjaan dari Caca dan Indro
- `iloc` untuk menampilkan domisili dan pekerjaan dari Caca dan Indro

In [25]:
df.loc[[2, 8],['Domisili', 'Pekerjaan']]

df.iloc[[2,8],[2,4]]

Umur       Pekerjaan
2    30  Data Scientist
8    30      BI Analyst

### **Nomor 8**
Tampilkan semua data yang berumur dibawah 30 tahun

In [21]:
df[df['Umur'] < 30]

Nama  Gender  Umur           Domisili      Pekerjaan       Hobi
0   Andi    Pria    24            Jakarta   Data Analyst     Gaming
1   Budi    Pria    25  Tangerang Selatan  Data Engineer     Futsal
4  Erika  Wanita    28            Jakarta   Data Analyst      Masak
5  Fahri    Pria    24           Surabaya  Data Engineer  Traveling
6   Gina  Wanita    29            Bandung    ML Engineer     Basket
9  Jarot    Pria    29  Tangerang Selatan   Data Analyst     Futsal

**9. Siapa sajakah yang berumur lebih dari 29 tahun dan hobinya Gaming?**

In [22]:
df[(df['Umur'] > 29) & (df['Hobi'] == 'Gaming')]

Nama Gender  Umur Domisili       Pekerjaan    Hobi
3   Dedi   Pria    32  Bandung  Data Scientist  Gaming
8  Indro   Pria    30  Jakarta      BI Analyst  Gaming